project:
  type: website

website:
  title: "Pensar la seguridad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
lang: es
format:
  html:
    theme:
      light: lux
      dark: slate
    css: styles.css

editor: visual

